const MAX_BUCKET_SIZE = 10;
const NUMBER_OF_REQUESTS = 5;
const WINDOW_SIZE_FOR_RATE_LIMIT_IN_MILLISECONDS = 10000;

const constants = {
    MAX_BUCKET_SIZE,
    NUMBER_OF_REQUESTS,
    WINDOW_SIZE_FOR_RATE_LIMIT_IN_MILLISECONDS
};

module.exports = constants;
